GET http://localhost:3000/links

###
POST http://localhost:3000/link/new
Content-Type: application/json

{
    "text": "https://translate.google.com/?hl=pt-BR",
    "label": "Google Translator",
    "tags": []
}

###
DELETE http://localhost:3000/link/delete/

//delete ALL
###
DELETE http://localhost:3000/link/deleteALL


###
PUT http://localhost:3000/link/edit/63ed0d2e14e8ae66baad173f
Content-Type: application/json

{
    "text": "test 3",
    "label": "teste 4"
}
