GET http://localhost:3000/links

###
POST http://localhost:3000/link/new
Content-Type: application/json

{
    "text": "test 2",
    "label": "label 2",
    "tags": ["css", "javascript", "mongoose", "node"]
}

###
DELETE http://localhost:3000/link/delete/63e3e08a382f2f0469c42192

//delete ALL
###
DELETE http://localhost:3000/link/deleteALL


###
PUT http://localhost:3000/link/edit/63e3e08a382f2f0469c42192
Content-Type: application/json

{
    "text": "test 3"
}
