GET https://link-api-gqiv.onrender.com/links

###
POST https://link-api-gqiv.onrender.com/link/new
Content-Type: application/json

{
    "text": "https://translate.google.com/?hl=pt-BR",
    "label": "Google Translator",
    "tags": []
}

###
DELETE http://localhost:3000/link/delete/63ed6a13f165c075f2044e19

//delete ALL
###
DELETE https://link-api-gqiv.onrender.com/link/deleteALL


###
PUT http://localhost:3000/link/edit/63ed0d2e14e8ae66baad173f
Content-Type: application/json

{
    "text": "test 3",
    "label": "teste 4"
}
